"""member number

Revision ID: 282842fa88cd
Revises: dbb8eb42637b
Create Date: 2026-10-07 16:21:06.892410

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "282842fa88cd"
down_revision: str | Sequence[str] | None = "dbb8eb42637b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("members", sa.Column("member_no", sa.Integer(), nullable=True))
    op.execute(
        "UPDATE members m SET member_no = s.no FROM ("
        "SELECT id, 1000 + ROW_NUMBER() OVER (PARTITION BY organization_id ORDER BY id) AS no "
        "FROM members) s WHERE m.id = s.id"
    )
    op.alter_column("members", "member_no", nullable=False)
    op.create_unique_constraint(
        "uq_members_org_member_no", "members", ["organization_id", "member_no"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_members_org_member_no", "members", type_="unique")
    op.drop_column("members", "member_no")
    # ### end Alembic commands ###
