"""meal end times, mark time, meal closures

Revision ID: 316873559800
Revises: 282842fa88cd
Create Date: 2026-10-07 16:52:39.427279

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "316873559800"
down_revision: str | Sequence[str] | None = "282842fa88cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meal_closures",
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "meal_type",
            postgresql.ENUM("lunch", "dinner", name="meal_type", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "date", "meal_type", name="uq_meal_closures_org_date_meal"
        ),
    )
    op.create_index(
        op.f("ix_meal_closures_organization_id"), "meal_closures", ["organization_id"], unique=False
    )
    op.add_column("attendance", sa.Column("marked_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "attendance", sa.Column("auto", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "organizations",
        sa.Column("lunch_end_time", sa.Time(), server_default="15:30", nullable=False),
    )
    op.add_column(
        "organizations",
        sa.Column("dinner_end_time", sa.Time(), server_default="23:00", nullable=False),
    )
    op.execute("UPDATE attendance SET marked_at = updated_at WHERE marked_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "dinner_end_time")
    op.drop_column("organizations", "lunch_end_time")
    op.drop_column("attendance", "auto")
    op.drop_column("attendance", "marked_at")
    op.drop_index(op.f("ix_meal_closures_organization_id"), table_name="meal_closures")
    op.drop_table("meal_closures")
    # ### end Alembic commands ###
