"""member type tiffin

Revision ID: 658611a8fd68
Revises: 977f15e2a5b0
Create Date: 2026-10-07 14:16:02.434984

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "658611a8fd68"
down_revision: str | Sequence[str] | None = "977f15e2a5b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    sa.Enum("dine_in", "tiffin", name="member_type").create(op.get_bind(), checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "members",
        sa.Column(
            "member_type",
            sa.Enum("dine_in", "tiffin", name="member_type"),
            server_default="dine_in",
            nullable=False,
        ),
    )
    op.add_column("members", sa.Column("company", sa.String(length=120), nullable=True))
    op.add_column("members", sa.Column("delivery_address", sa.String(length=300), nullable=True))
    op.create_index(
        "ix_members_org_type", "members", ["organization_id", "member_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_members_org_type", table_name="members")
    op.drop_column("members", "delivery_address")
    op.drop_column("members", "company")
    op.drop_column("members", "member_type")
    sa.Enum(name="member_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
