"""pricing and plan kind

Revision ID: 842f25cf0eb5
Revises: c067742f33ca
Create Date: 2026-10-07 15:57:01.521836

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "842f25cf0eb5"
down_revision: str | Sequence[str] | None = "c067742f33ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mess_plans", sa.Column("kind", sa.String(length=20), nullable=True))
    op.create_unique_constraint("uq_mess_plans_org_kind", "mess_plans", ["organization_id", "kind"])
    op.add_column(
        "organizations",
        sa.Column("one_meal_price", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "organizations",
        sa.Column("two_meal_price", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "two_meal_price")
    op.drop_column("organizations", "one_meal_price")
    op.drop_constraint("uq_mess_plans_org_kind", "mess_plans", type_="unique")
    op.drop_column("mess_plans", "kind")
    # ### end Alembic commands ###
