"""attendance holidays month closures leaves

Revision ID: 8d09908195a1
Revises: e308cd5bdf98
Create Date: 2026-10-07 14:05:22.392716

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d09908195a1"
down_revision: str | Sequence[str] | None = "e308cd5bdf98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holidays",
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "meal_type", sa.Enum("lunch", "dinner", "all", name="holiday_meal"), nullable=False
        ),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "date", "meal_type", name="uq_holidays_org_date_meal"
        ),
    )
    op.create_index(
        op.f("ix_holidays_organization_id"), "holidays", ["organization_id"], unique=False
    )
    op.create_table(
        "month_closures",
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_by", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["closed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "month", name="uq_month_closures_org_month"),
    )
    op.create_index(
        op.f("ix_month_closures_organization_id"),
        "month_closures",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "attendance",
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("meal_type", sa.Enum("lunch", "dinner", name="meal_type"), nullable=False),
        sa.Column("status", sa.Enum("present", "absent", name="attendance_status"), nullable=False),
        sa.Column("marked_by", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["marked_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "member_id", "date", "meal_type", name="uq_attendance_member_date_meal"
        ),
    )
    op.create_index(
        "ix_attendance_org_date_meal",
        "attendance",
        ["organization_id", "date", "meal_type"],
        unique=False,
    )
    op.create_table(
        "leaves",
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("meal_type", sa.Enum("lunch", "dinner", name="meal_type"), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column(
            "status", sa.Enum("approved", "late", "rejected", name="leave_status"), nullable=False
        ),
        sa.Column("decided_by", sa.BigInteger(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["decided_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "date", "meal_type", name="uq_leaves_member_date_meal"),
    )
    op.create_index("ix_leaves_org_date", "leaves", ["organization_id", "date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_leaves_org_date", table_name="leaves")
    op.drop_table("leaves")
    op.drop_index("ix_attendance_org_date_meal", table_name="attendance")
    op.drop_table("attendance")
    op.drop_index(op.f("ix_month_closures_organization_id"), table_name="month_closures")
    op.drop_table("month_closures")
    op.drop_index(op.f("ix_holidays_organization_id"), table_name="holidays")
    op.drop_table("holidays")
    # ### end Alembic commands ###
