"""member next plan

Revision ID: 94a27cb96935
Revises: 316873559800
Create Date: 2026-10-07 17:07:34.017185

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94a27cb96935"
down_revision: str | Sequence[str] | None = "316873559800"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("members", sa.Column("next_plan_id", sa.BigInteger(), nullable=True))
    op.add_column("members", sa.Column("next_plan_from", sa.Date(), nullable=True))
    op.create_foreign_key(
        None, "members", "mess_plans", ["next_plan_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "members", type_="foreignkey")
    op.drop_column("members", "next_plan_from")
    op.drop_column("members", "next_plan_id")
    # ### end Alembic commands ###
