"""bulk tiffin clients orders payments

Revision ID: c067742f33ca
Revises: 4143dda4ec87
Create Date: 2026-10-07 15:43:11.849741

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c067742f33ca"
down_revision: str | Sequence[str] | None = "4143dda4ec87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tiffin_clients",
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("contact_name", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=15), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("veg_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("nonveg_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tiffin_clients_organization_id"),
        "tiffin_clients",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "tiffin_orders",
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "meal_type",
            postgresql.ENUM("lunch", "dinner", name="meal_type", create_type=False),
            nullable=False,
        ),
        sa.Column("veg_count", sa.Integer(), nullable=False),
        sa.Column("nonveg_count", sa.Integer(), nullable=False),
        sa.Column("veg_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("nonveg_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["tiffin_clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "client_id", "date", "meal_type", name="uq_tiffin_orders_client_date_meal"
        ),
    )
    op.create_index(
        "ix_tiffin_orders_org_date", "tiffin_orders", ["organization_id", "date"], unique=False
    )
    op.create_table(
        "tiffin_payments",
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "method",
            postgresql.ENUM("cash", "upi", "bank", name="payment_method", create_type=False),
            nullable=False,
        ),
        sa.Column("paid_on", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("recorded_by", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["tiffin_clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recorded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tiffin_payments_client_month", "tiffin_payments", ["client_id", "month"], unique=False
    )
    op.create_index(
        op.f("ix_tiffin_payments_organization_id"),
        "tiffin_payments",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tiffin_payments_organization_id"), table_name="tiffin_payments")
    op.drop_index("ix_tiffin_payments_client_month", table_name="tiffin_payments")
    op.drop_table("tiffin_payments")
    op.drop_index("ix_tiffin_orders_org_date", table_name="tiffin_orders")
    op.drop_table("tiffin_orders")
    op.drop_index(op.f("ix_tiffin_clients_organization_id"), table_name="tiffin_clients")
    op.drop_table("tiffin_clients")
    # ### end Alembic commands ###
