"""tiffin price list and order lines

Revision ID: dbb8eb42637b
Revises: f809253e5f8e
Create Date: 2026-10-07 16:14:44.468885

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbb8eb42637b"
down_revision: str | Sequence[str] | None = "f809253e5f8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Old orders stored only veg/non-veg counts; they cannot map to price-list items.
    op.execute("DELETE FROM tiffin_orders")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tiffin_items",
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("food_type", sa.Enum("veg", "egg", "nonveg", name="food_type"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tiffin_items_organization_id"), "tiffin_items", ["organization_id"], unique=False
    )
    op.create_table(
        "tiffin_order_lines",
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("item_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["tiffin_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["tiffin_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", "item_id", name="uq_tiffin_lines_order_item"),
    )
    op.create_index(
        op.f("ix_tiffin_order_lines_order_id"), "tiffin_order_lines", ["order_id"], unique=False
    )
    op.drop_column("tiffin_clients", "nonveg_rate")
    op.drop_column("tiffin_clients", "veg_rate")
    op.drop_column("tiffin_orders", "nonveg_count")
    op.drop_column("tiffin_orders", "veg_count")
    op.drop_column("tiffin_orders", "nonveg_rate")
    op.drop_column("tiffin_orders", "veg_rate")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tiffin_orders",
        sa.Column(
            "veg_rate", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "tiffin_orders",
        sa.Column(
            "nonveg_rate", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "tiffin_orders", sa.Column("veg_count", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "tiffin_orders",
        sa.Column("nonveg_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "tiffin_clients",
        sa.Column(
            "veg_rate", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "tiffin_clients",
        sa.Column(
            "nonveg_rate", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_tiffin_order_lines_order_id"), table_name="tiffin_order_lines")
    op.drop_table("tiffin_order_lines")
    op.drop_index(op.f("ix_tiffin_items_organization_id"), table_name="tiffin_items")
    op.drop_table("tiffin_items")
    # ### end Alembic commands ###
