"""plans and members

Revision ID: e308cd5bdf98
Revises: 31b700f0af71
Create Date: 2026-10-07 13:55:46.653284

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e308cd5bdf98"
down_revision: str | Sequence[str] | None = "31b700f0af71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mess_plans",
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("includes_lunch", sa.Boolean(), nullable=False),
        sa.Column("includes_dinner", sa.Boolean(), nullable=False),
        sa.Column("monthly_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mess_plans_organization_id"), "mess_plans", ["organization_id"], unique=False
    )
    op.create_table(
        "members",
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=15), nullable=False),
        sa.Column("room_no", sa.String(length=30), nullable=True),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("monthly_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("joining_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Enum("active", "inactive", name="member_status"), nullable=False),
        sa.Column("deposit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("emergency_contact", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("inactive_from", sa.Date(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["mess_plans.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index("ix_members_org_phone", "members", ["organization_id", "phone"], unique=False)
    op.create_index("ix_members_org_status", "members", ["organization_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_members_org_status", table_name="members")
    op.drop_index("ix_members_org_phone", table_name="members")
    op.drop_table("members")
    op.drop_index(op.f("ix_mess_plans_organization_id"), table_name="mess_plans")
    op.drop_table("mess_plans")
    # ### end Alembic commands ###
