"""membership periods

Revision ID: f809253e5f8e
Revises: 842f25cf0eb5
Create Date: 2026-10-07 16:03:11.592677

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f809253e5f8e"
down_revision: str | Sequence[str] | None = "842f25cf0eb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bills", sa.Column("period_start", sa.Date(), nullable=True))
    op.add_column("bills", sa.Column("period_end", sa.Date(), nullable=True))
    op.add_column("members", sa.Column("valid_until", sa.Date(), nullable=True))
    op.add_column("members", sa.Column("renewal_plan_id", sa.BigInteger(), nullable=True))
    op.add_column(
        "members", sa.Column("renewal_requested_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_foreign_key(
        None, "members", "mess_plans", ["renewal_plan_id"], ["id"], ondelete="SET NULL"
    )
    # backfill: legacy bills cover their calendar month; members valid to the end of their
    # latest billed month, or one month from joining when never billed
    op.execute(
        "UPDATE bills SET period_start = month, "
        "period_end = (month + interval '1 month' - interval '1 day')::date "
        "WHERE period_start IS NULL"
    )
    op.execute(
        "UPDATE members m SET valid_until = COALESCE("
        "(SELECT MAX(b.period_end) FROM bills b WHERE b.member_id = m.id), "
        "(m.joining_date + interval '1 month' - interval '1 day')::date) "
        "WHERE valid_until IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "members", type_="foreignkey")
    op.drop_column("members", "renewal_requested_at")
    op.drop_column("members", "renewal_plan_id")
    op.drop_column("members", "valid_until")
    op.drop_column("bills", "period_end")
    op.drop_column("bills", "period_start")
    # ### end Alembic commands ###
